services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orangehrm
      MYSQL_INITDB_SKIP_TZINFO: "1"
    ports:
      - "3306:3306"
    volumes:
      - ./orangehrm-db-seed.sql:/docker-entrypoint-initdb.d/orangehrm-db-seed.sql
    command: --innodb-force-recovery=0 --max_allowed_packet=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  orangehrm:
    image: orangehrm/orangehrm:latest
    ports:
      - "3000:80"
    depends_on:
      mysql:
        condition: service_healthy